apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-machine-set-operator
  namespace: openshift-machine-api
  labels:
    k8s-app: control-plane-machine-set-operator
  annotations:
    capability.openshift.io/name: MachineAPI
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: control-plane-machine-set-operator
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: restricted-v2
      labels:
        k8s-app: control-plane-machine-set-operator
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: control-plane-machine-set-operator
      containers:
      - name: control-plane-machine-set-operator
        image: quay.io/openshift/origin-cluster-control-plane-machine-set-operator
        command:
        - "/manager"
        args:
        - -v=4
        - --leader-elect=true
        - --leader-elect-lease-duration=137s
        - --leader-elect-renew-deadline=107s
        - --leader-elect-retry-period=26s
        - --leader-elect-resource-namespace=openshift-machine-api
        env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        - name: COMPONENT_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - name: https
          containerPort: 9443
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: control-plane-machine-set-operator-tls
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: control-plane-machine-set-operator-tls
        secret:
          defaultMode: 420
          secretName: control-plane-machine-set-operator-tls
